-- Find the total number of orders placed by each customer.
SELECT customer_id, COUNT(*)
FROM orders
GROUP BY customer_id;

-- Find the total revenue generated by each customer.
SELECT customer_id, SUM(order_amount)
FROM orders
GROUP BY customer_id;

-- Find customers whose total revenue is greater than 30,000.
SELECT customer_id, SUM(order_amount) AS total_revenue
FROM orders
GROUP BY customer_id
HAVING total_revenue > 30000;

-- Find the average order amount per customer.
SELECT customer_id, AVG(order_amount)
FROM orders
GROUP BY customer_id;

-- Find customers who have placed more than 2 orders.
SELECT customer_id, COUNT(*) AS total_order
FROM orders
GROUP BY customer_id
HAVING total_order > 2;

-- Find the top 3 customers by total revenue.
SELECT customer_id, SUM(order_amount) AS total_revenue
FROM orders
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 3;

-- Find customers whose average order value is greater than 15,000.
SELECT customer_id, AVG(order_amount) AS avg_revenue
FROM orders
GROUP BY customer_id
HAVING avg_revenue > 15000;

-- Find customers who placed their first order in 2024.
SELECT customer_id
FROM orders
GROUP BY customer_id
HAVING YEAR(MIN(order_date)) = 2024;