-- Find the total quantity sold for each product.
SELECT product_name, SUM(quantity)
FROM order_items
GROUP BY product_name;

-- Find products whose total quantity sold is greater than 2.
SELECT product_name
FROM order_items
GROUP BY product_name
HAVING SUM(quantity) > 2;

-- Find the total revenue generated by each product
-- (quantity × price).
SELECT product_name,
       SUM(quantity * price) AS total_revenue
FROM order_items
GROUP BY product_name;

-- Find the top 3 products by total revenue.
SELECT product_name,
       SUM(quantity * price) AS total_revenue
FROM order_items
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 3;

-- Find the average quantity sold per product.
SELECT product_name, AVG(quantity)
FROM order_items
GROUP BY product_name;
